AWSTemplateFormatVersion: "2010-09-09"

Description: >
  An application defined by https://github.com/nchlswhttkr/build-breaker

Transform: "AWS::Serverless-2016-10-31"

Parameters:
  LambdaCodeBucket:
    Type: String
    Description: The ID of the bucket containing the code to run Lambdas off
  BuildBreakerVersion:
    Type: String
    Description: A version identifier to force code/deployment updates
    Default: initial
  StageName:
    Type: String
    Description: The name of the stage that the API will be deployed to
    Default: production

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Description: The role which functions execute with
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: BuildBreakerCloudwatchLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: logs:*
                Resource: "*"

  BuildBreakerApi:
    Type: AWS::Serverless::Api
    Description: Creates an API that can be used to trigger functions
    Properties:
      Name: BuildBreakerApi
      StageName: !Ref StageName

  # HelloWorldFunction
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Description: A hello world function for build-breaker
    Properties:
      CodeUri:
        Bucket: !Ref LambdaCodeBucket
        Key: !Sub "handlers/${BuildBreakerVersion}/hello.zip"
      Handler: bin/hello
      Runtime: go1.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        HelloFunctionApiTrigger:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref BuildBreakerApi

  # TipFunction
  TipFunction:
    Type: AWS::Serverless::Function
    Description: A tip function called when a build fails
    Properties:
      CodeUri:
        Bucket: !Ref LambdaCodeBucket
        Key: !Sub "handlers/${BuildBreakerVersion}/tip.zip"
      Handler: bin/tip
      Runtime: go1.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        TipFunctionApiTrigger:
          Type: Api
          Properties:
            Path: /tip/{provider}
            Method: POST
            RestApiId: !Ref BuildBreakerApi

Outputs:
  ApiUrl:
    Description: The URL that can be used to access the backend
    Value: !Sub "https://${BuildBreakerApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
  HelloWorldUrl:
    Description: The URL that can be used to trigger HelloWorldFunction
    Value: !Sub "https://${BuildBreakerApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/hello"
