AWSTemplateFormatVersion: "2010-09-09"

Description: >
  The template for https://github.com/nchlswhttkr/build-breaker

  This stack uses the following resources, please be aware that you may incur
  billing costs!
    - Lambda
    - S3 (to upload your binaries)

Transform: "AWS::Serverless-2016-10-31"

Parameters:
  LambdaExecutionRole:
    Type: String
    Description: The role which lambda functions execute with
  LambdaCodeBucket:
    Type: String
    Description: The ID of the bucket containing the code to run Lambdas off
  BuildBreakerVersion:
    Type: String
    Description: A version identifier to force code/deployment updates
  StageName:
    Type: String
    Description: The name of the stage that the API will be deployed to
    Default: production

Resources:
  BuildBreakerApi:
    Type: AWS::Serverless::Api
    Description: Creates an API that can be used to trigger functions
    Properties:
      Name: BuildBreakerApi
      StageName: !Ref StageName

  # HelloWorldFunction
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Description: A hello world function for build-breaker
    Properties:
      CodeUri:
        Bucket: !Ref LambdaCodeBucket
        Key: !Sub "handlers/${BuildBreakerVersion}/hello.zip"
      Handler: bin/hello
      Runtime: go1.x
      Role: !Ref LambdaExecutionRole
      Events:
        HelloFunctionApiTrigger:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref BuildBreakerApi

  # TipFunction
  TipFunction:
    Type: AWS::Serverless::Function
    Description: A tip function called when a build fails
    Properties:
      CodeUri:
        Bucket: !Ref LambdaCodeBucket
        Key: !Sub "handlers/${BuildBreakerVersion}/tip.zip"
      Handler: bin/tip
      Runtime: go1.x
      Role: !Ref LambdaExecutionRole
      Events:
        TipFunctionApiTrigger:
          Type: Api
          Properties:
            Path: /tip/{provider}
            Method: POST
            RestApiId: !Ref BuildBreakerApi

Outputs:
  ApiUrl:
    Description: The URL that can be used to access the backend
    Value: !Sub "https://${BuildBreakerApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
  HelloWorldUrl:
    Description: The URL that can be used to trigger HelloWorldFunction
    Value: !Sub "https://${BuildBreakerApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/hello"
